version: '3'

services:
  api:
    build: ./src/api
    depends_on:
      - db
    env_file:
      - '.env'
    volumes:
      - ./src/api:/app
    ports:
      - 3000:3000

  client:
    build: ./src/client
    env_file:
      - '.env'
    volumes:
      - ./src/client:/app
    ports:
      - 8080:8080

  db:
    image: postgres:11-alpine
    env_file:
      - '.env'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
