source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 3.11'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0.rc1'

# A plain-Ruby implementation of GraphQL
gem 'graphql', '~> 1.9', '>= 1.9.4'

# Adds simple rake commands for seeding your database
gem 'seedbank', '~> 0.5.0'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # A framework and DSL for defining and using factories
  gem 'factory_bot_rails', '~> 5.0', '>= 5.0.2'

  # Easily generate fake data: names, addresses, phone numbers, etc.
  gem 'faker', '~> 1.9', '>= 1.9.3'

  # A testing framework for Rails 3+
  gem 'rspec-rails', '~> 3', '>= 3.8.2'
end

group :test do
  # Strategies for cleaning databases. Can be used to ensure a clean state for testing
  gem 'database_cleaner', '~> 1.7'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
